#!/bin/bash
x="$(samtools view selected.bam|wc -l)"
for (( c=1; c<=$x; c++ ))
do  
	 samtools view -H selected.bam > tmpwithHeader.sam
   samtools view selected.bam | awk '{if(NR=='$c')print$0}' >> tmpwithHeader.sam
   samtools bam2fq tmpwithHeader.sam > tmp.fastq
   ngmlr -t 4 -r tmp.fasta -q Ref/alt.fastq -o test.sam
   rm -f tmpwithHeader.sam
   rm -f tmp.fastq
done 

