#!/bin/bash
x="$(samtools view selected.bam|wc -l)"
for (( c=1; c<=$x; c++ ))
do  
	 samtools view -H selected.bam > tmpwithHeader.sam
   samtools view selected.bam | awk '{if(NR=='$c')print$0}' >> tmpwithHeader.sam
   samtools bam2fq tmpwithHeader.sam > tmp.fastq
   ngmlr -t 4 -r tmp.fasta -q Ref/alt.fastq -o test.sam
   samtools view test.sam >> results.sam
   rm -f test.sam
   rm -f tmpwithHeader.sam
   rm -f tmp.fastq
done 









#!/bin/bash

	 samtools view -H selected.bam > tmpwithHeader.sam
   samtools view selected.bam | awk '{if(NR==1)print$0}' >> tmpwithHeader.sam
   samtools bam2fq tmpwithHeader.sam > tmp.fastq
   ngmlr -t 4 -r tmp.fasta -q Ref/alt.fastq -o test.sam
   samtools view test.sam >> results.sam
   rm -f test.sam
   rm -f tmpwithHeader.sam
   rm -f tmp.fastq
   
   samtools view -H selected.bam > tmpwithHeader.sam
   samtools view selected.bam | awk '{if(NR==2)print$0}' >> tmpwithHeader.sam
   samtools bam2fq tmpwithHeader.sam > tmp.fastq
   ngmlr -t 4 -r tmp.fasta -q Ref/alt.fastq -o test.sam
   samtools view test.sam >> results.sam
   rm -f test.sam
   rm -f tmpwithHeader.sam
   rm -f tmp.f
   
   samtools view -H selected.bam > tmpwithHeader.sam
   samtools view selected.bam | awk '{if(NR==3)print$0}' >> tmpwithHeader.sam
   samtools bam2fq tmpwithHeader.sam > tmp.fastq
   ngmlr -t 4 -r tmp.fasta -q Ref/alt.fastq -o test.sam
   samtools view test.sam >> results.sam
   rm -f test.sam
   rm -f tmpwithHeader.sam
   rm -f tmp.fastq
 


